### ISSUE TITLE
LXC on android

### ISSUE THREAD

**Issue by SaicharanKandukuri** [WMCB-Tech/DebDroid#8]
recently when I tried to unzip and decrypt Samsung Linux on dex with apktool I found files of LXC like liblxc.so in it
Is there any chance we can implement it in android with termux or any other way? like they did

**Comment by WMCB-Tech** [comment]
@SaicharanKandukuri Idk if lxc will work on proot

But the interesting to know is why lxc works on linux on dex without root

Try to make an issue in GitHub (Termux root packages) about this

But since DebDroid uses proot as it's core, containerization won't work unless if there's some Emulation

DebDroid is already a container and applied some several walkarounds to make some utilities work as possible
